---
title: "Documenting R Classes"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Documenting R Classes}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
LOCAL <- identical(Sys.getenv("R_LOCAL"), "TRUE")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  purl = LOCAL
)
```

```{r setup, echo = FALSE}

 #library(umlr2)
source("../R/R6UMLREnum.R")
source("../R/R6Messages.R")
source("../R/R6Template.R")
source("../R/R6Config.R")
source("../R/R6UMLRBase.R")
files.r = list.files("../R", pattern="*\\.R$", full.names=TRUE, ignore.case=F)
xx = sapply(files.r, source)

uml = UML$new(plantuml="C:\\SDK\\plantuml\\plantuml.jar")
umlr = UMLR$new(plantuml="C:\\SDK\\plantuml\\plantuml.jar")
```

# Intro

El paquete provee una clase para generar definiciones UML de objetos R.
Actualmente es posible procesar:

- Clases R6
- Clases S4 

El proceso general consiste en crear un objeto **UMLR** y ejecutar el metodo `plotClass`:

```{r}
 umlr$plotClass(c(uml, umlr), UMLShow$basic)
```

simple

```{r}
 umlr$plotClass(c(uml, umlr), UMLShow$simple)
```


con padres
```{r}
base = UMLShow$complete + UMLShow$superClasses
 umlr$plotClass(c(uml, umlr), base)
```

completo

```{r}
base = UMLShow$complete + UMLShow$superClasses + UMLShow$subClasses
 umlr$plotClass(c(uml, umlr), base, deep=10)
```



